# env:
  # global:
  # - PYTHONIOENCODING=utf-8
jobs:
  include:
    - os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install: choco install --x86 python
    - os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install: choco install python
      script:
      - pyinstaller --onefile __main__.py -n LuaObfuscator
      - ls ./dist
      - zip -r ./LuaObfuscator-win-x64 ./dist
      - ls ./
    - os: linux
      language: python
      python: "3.6"    # 3.6 works!
    - os: osx
      language: generic
cache:
  directories:
    - ./dist
addons:
  apt:
    packages:
      - zip
install:
- pip install pyinstaller

branches:
  only:
    - master

script:
- pyinstaller --onefile __main__.py -n LuaObfuscator
- ls ./dist
- |
  if [ $TRAVIS_OS_NAME != "windows" ]; then
    zip -r ./LuaObfuscator-$TRAVIS_OS_NAME ./dist
  else
    zip -r ./LuaObfuscator-win-x32 ./dist
  fi
- ls ./

before_deploy:
- export TRAVIS_TAG=$(date +'%Y.%m.%d')
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ./LuaObfuscator-*
  skip_cleanup: true
  name: $(date +'%Y.%m.%d')
  on:
    branch: master
