# env:
  # global:
  # - PYTHONIOENCODING=utf-8

jobs:
  include:
    - os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
      - choco install --x86 python
    - os: linux
      language: python
      # dist: xenial   # ↓
      python: "3.6"    # 3.6 works!
    - os: osx
      language: generic

install:
- pip install pyinstaller

branches:
  only:
    - master

script:
- pyinstaller --onefile __main__.py -n LuaObfuscator
- ls ./dist
before_deploy:
- export TRAVIS_TAG=$(date +'%Y.%m.%d')
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ./dist/LuaObfuscator*
  skip_cleanup: true
  name: $(date +'%Y.%m.%d-%H_%M_%S') - $TRAVIS_OS_NAME
  on:
    branch: master
