# env:
  # global:
  # - PYTHONIOENCODING=utf-8
jobs:
  include:
    - os: windows
      language: shell
      env: SOSAT=x32
      before_install:
      - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
      - choco install --x86 python3
      - choco install zip
    - os: windows
      language: shell
      env: SOSAT=x64
      before_install:
      - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
      - choco install python3
      - choco install zip
    - os: linux
      language: python
      python: "3.6"    # 3.6 works!
    - os: osx
      language: generic

install:
- pip install pyinstaller

branches:
  only:
    - master

script:
- pyinstaller --onefile __main__.py -n LuaObfuscator
- ls ./dist
- |
  if [ $TRAVIS_OS_NAME != "windows" ]; then
    zip -r ./LuaObfuscator-$TRAVIS_OS_NAME ./dist
  else
    zip -r ./LuaObfuscator-win-$SOSAT ./dist
  fi

before_deploy:
- export TRAVIS_TAG=$(date +'%Y.%m.%d-%H_%M_%S')
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ./LuaObfuscator-*
  skip_cleanup: true
  name: $(date +'%Y.%m.%d-%H_%M_%S')
  on:
    branch: master
